apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJUV2x6YUdsdVlVeGhibUU2WjJod1gwVlZNRXc1UTJkMmVuaExRemRaV0RSVFpURXlVVFV4Ym5WaFRVZDZSekIzYWtvM1NBPT0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogIm9zeGtleWNoYWluIiwKCSJjdXJyZW50Q29udGV4dCI6ICJvcmJzdGFjayIKfQo=
type: kubernetes.io/dockerconfigjson
